### ISSUE TITLE
Circular loading indicator is laggy and wonky

### ISSUE THREAD

**Issue by dicarlo2** [neotracker/neotracker#5]
Most prevalent on Open Wallet/New Wallet pages when opening/creating a wallet.

**Comment by afragapane** [comment]
Things tried/learned:
-Switching to the material-ui CircularProgress loading indicator gives similar behavior. 
-Displaying the loading indicator before the unlock button is pressed works just fine.
-There is no sketchy logic with the loading, loading is always "true" during unlock and "false" otherwise.
-Refactoring the loading check to be more explicit does not change the behavior.  
-Other portions of the site are a bit laggy on loading.  e.g. the initial loading screen is rarely smooth.
-Other people seem to have had very similar issues:
https://github.com/mui-org/material-ui/issues/2232
https://github.com/mui-org/material-ui/issues/707

I am wondering if this has more to do with the expensive processes running while the wallet is loading than the loading indicator itself.
